TRUNCATE TABLE Review CASCADE;
TRUNCATE TABLE writes CASCADE;
TRUNCATE TABLE order_item CASCADE;
TRUNCATE TABLE orders CASCADE;
TRUNCATE TABLE book CASCADE;
TRUNCATE TABLE report CASCADE;
TRUNCATE TABLE publisher CASCADE;
TRUNCATE TABLE author CASCADE;
TRUNCATE TABLE customer CASCADE;
TRUNCATE TABLE users CASCADE;


