TRUNCATE TABLE Review CASCADE;
TRUNCATE TABLE writes CASCADE;
TRUNCATE TABLE order_item CASCADE;
TRUNCATE TABLE orders CASCADE;
TRUNCATE TABLE book CASCADE;
TRUNCATE TABLE report CASCADE;
TRUNCATE TABLE publisher CASCADE;
TRUNCATE TABLE author CASCADE;
TRUNCATE TABLE customer CASCADE;
TRUNCATE TABLE users CASCADE;

DROP TABLE review;
DROP TABLE writes;
DROP TABLE order_item;
DROP TABLE orders;
DROP TABLE book;
DROP TABLE report;
DROP TABLE publisher;
DROP TABLE author;
DROP TABLE customer;
DROP TABLE users;

